### ISSUE TITLE
Option to just remove the "put.io" prefix

### ISSUE THREAD

**Issue by ajarang** [girlfriend-technology/magnet-links-extension#1]
first off, thank you for the extension. I can't believe apple won't even let me copy magnet links. 

It would be nice if there was an option to get rid of the "https://put.io/default" prefix, so I can just copy the magnet link itself.

**Comment by ZicklePop** [comment]
Ugh it is so annoying you can't copy magnet links. I like this idea a lot, and have been thinking of ways to make it less Put.io specific, but I hadn't considered copying.

**Comment by ZicklePop** [comment]
This feature is available in the latest version for Safari, Chrome, and Firefox. Edge reviews take a while. I hope you enjoy :)
