### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Kajover** [girlfriend-technology/magnet-links-extension#3]
Thank you for this great app. Some feedback:

Please add
- a discussion page on github (or some way to contact the dev)
- a donation button in the app/website
- a help page for the prefixes on how to use it with other pages (for instance, for qBittorrent's WebUI)

**Comment by ZicklePop** [comment]
Hey there! Thanks for the feedback!

I've never used GitHub Discussions before, but I've turned them on. Will make an announcement post soon.

For donations, I've had decided against it for a few reasons but I could totally change my mind. I feel like I would rather encourage people donate to [Trans Lifeline](https://translifeline.org/) personally.

I'd love to help more options be in the list, I just didn't know any off the top of my head and custom prefixes was a quick way for me to hopefully empower people, but I agree it could (and will) be a lot better. I am definitely open to suggestions and will make a note of qBittorrent. I also have to keep in mind certain app store and extension store review policies, so yeah maybe a help page for things that could get flagged.

**Comment by Kajover** [comment]
Thank you.
I really appreciate the app, and I hope it never ceases to exist because of monetary issues. That is why I thought a donation button might help. However, donating to another person/organization/etc. is a good alternative as well :)
